### ISSUE TITLE
Cannot find module '../dist/src/index'

### ISSUE THREAD

**Issue by duszans** [paulkoerbitz/tslint-auto-disable#3]
It seems that tslint-auto-disable npm package doesn't contain built js files.

**Steps to reproduce**
1. npx tslint-auto-disable -p tsconfig.json -c tslint.json

**Expected**
The `tslint:disable-next-line` comments are added.

**Actual**
```
npx: installed 42 in 17.046s
Cannot find module '../dist/src/index'
```

**Environment**
- WSL (windows subsystem for linux), Ubuntu, Linux ********* 4.4.0-17763-Microsoft #55-Microsoft Sat Oct 06 18:05:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
- `node -v`: v8.9.4
- `npm -v`: 5.6.0
- `"typescript": "^3.1.6"`
- `"tslint": "^5.11.0"`

**Comment by lesyk** [comment]
@duszans added missing files: https://github.com/paulkoerbitz/tslint-auto-disable/pull/4

However, @paulkoerbitz all tests do fail.

**Comment by paulkoerbitz** [comment]
OK, so I finally got around to solving this. The built files were ignored by the automatic npm ignore settings. Thanks a lot for the feedback, I apologize that it took me this long to see this.
